# Numpy


In [1]:
import numpy as np


#DataTypes & Attributes

In [4]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [6]:
 np.shape(a1)

(3,)

In [7]:
a1.ndim

1

In [8]:
a2 = np.array([[1,2,3], [4,5,6]])

In [10]:
np.shape(a2)

(2, 3)

In [11]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a2.ndim

2

In [13]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
import pandas as pd

In [15]:
df = pd.DataFrame(a2)

In [16]:
df

0  1  2
0  1  2  3
1  4  5  6

## Creating Arrays

In [18]:
ones = np.ones((2,3))

In [19]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
type(ones)

numpy.ndarray

In [24]:
zeros = np.zeros((2,3))

In [25]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
range_array = np.arange(0,10,2)

In [27]:
range_array

array([0, 2, 4, 6, 8])

In [31]:
random_array = np.random.randint(1,10,size=(2,3))

In [32]:
random_array

array([[4, 2, 1],
       [6, 2, 3]])

In [33]:
np.random.random((3,6))

array([[0.90639748, 0.31400951, 0.18011621, 0.1833942 , 0.70636206,
        0.21160528],
       [0.70470682, 0.04327064, 0.78750801, 0.93865414, 0.86786923,
        0.6223984 ],
       [0.98439665, 0.7439711 , 0.92328098, 0.57357301, 0.69737307,
        0.01761596]])

In [34]:
r3 = np.random.rand(2,3)

In [35]:
r3


array([[0.65144709, 0.30424004, 0.96190122],
       [0.62553107, 0.55990965, 0.42066815]])

In [48]:
# Pseudo random number
np.random.seed(0)

In [49]:
np.random.randint(10, size=(2,3))

array([[5, 0, 3],
       [3, 7, 9]])

## Viewing arrays in Numpy

In [71]:
a1 = np.array([1,2,3,4])

In [72]:
a2 = np.array([a1, a1, a1])

In [73]:
a3 = np.array([a2,a2,a2])

In [74]:
a1

array([1, 2, 3, 4])

In [75]:
a2

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [76]:
a3

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [77]:
a3.ndim

3

In [78]:
a2.ndim

2

In [79]:
a1[0], a2[0], a3[0]

(1,
 array([1, 2, 3, 4]),
 array([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]))

In [80]:
np.shape(a2), np.shape(a3)

((3, 4), (3, 3, 4))

In [81]:
a3[0][0]

array([1, 2, 3, 4])

In [82]:
a3[0][0][1]

2

In [83]:
a1.shape, a2.shape, a3.shape

((4,), (3, 4), (3, 3, 4))

In [84]:
a4 = np.random.randint(10, size=(2,3,4,5))

In [85]:
a4


array([[[[3, 5, 2, 4, 7],
         [6, 8, 8, 1, 6],
         [7, 7, 8, 1, 5],
         [9, 8, 9, 4, 3]],

        [[0, 3, 5, 0, 2],
         [3, 8, 1, 3, 3],
         [3, 7, 0, 1, 9],
         [9, 0, 4, 7, 3]],

        [[2, 7, 2, 0, 0],
         [4, 5, 5, 6, 8],
         [4, 1, 4, 9, 8],
         [1, 1, 7, 9, 9]]],


       [[[3, 6, 7, 2, 0],
         [3, 5, 9, 4, 4],
         [6, 4, 4, 3, 4],
         [4, 8, 4, 3, 7]],

        [[5, 5, 0, 1, 5],
         [9, 3, 0, 5, 0],
         [1, 2, 4, 2, 0],
         [3, 2, 0, 7, 5]],

        [[9, 0, 2, 7, 2],
         [9, 2, 3, 3, 2],
         [3, 4, 1, 2, 9],
         [1, 4, 6, 8, 2]]]])

In [86]:
a4[1
  ]

array([[[3, 6, 7, 2, 0],
        [3, 5, 9, 4, 4],
        [6, 4, 4, 3, 4],
        [4, 8, 4, 3, 7]],

       [[5, 5, 0, 1, 5],
        [9, 3, 0, 5, 0],
        [1, 2, 4, 2, 0],
        [3, 2, 0, 7, 5]],

       [[9, 0, 2, 7, 2],
        [9, 2, 3, 3, 2],
        [3, 4, 1, 2, 9],
        [1, 4, 6, 8, 2]]])

In [89]:
a4[1][1]

array([[5, 5, 0, 1, 5],
       [9, 3, 0, 5, 0],
       [1, 2, 4, 2, 0],
       [3, 2, 0, 7, 5]])

In [92]:
a4[:,:1,:3,:1]

array([[[[3],
         [6],
         [7]]],


       [[[3],
         [3],
         [6]]]])