In [2]:
import numpy as np


In [3]:
n = np.array([1,2,])

In [5]:
type(n)

numpy.ndarray

In [7]:
a = [[1,2,3],[5,6,7]]

In [8]:
n1 = np.array(a)

# 

In [9]:
n1


array([[1, 2, 3],
       [5, 6, 7]])

In [10]:
np.arange(1,33)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.zeros((2,3)) #rows, columns


array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.linspace(1,2,3)

array([1. , 1.5, 2. ])

In [19]:
np.linspace(1,10,11) #how many numbers you want between start and end is last param. 

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

In [17]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [21]:
#to create an identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(4)

array([0.90674198, 0.86280022, 0.25579347, 0.48476321])

In [24]:
np.random.rand(2,5)

array([[0.42553257, 0.47866733, 0.59005316, 0.94547662, 0.26465503],
       [0.92214505, 0.70018012, 0.42393725, 0.51692765, 0.92471833]])

In [25]:
np.random.rand(1)

array([0.31379867])

In [28]:
np.random.rand(2,3)

array([[0.19269861, 0.62645622, 0.39470889],
       [0.08469158, 0.96723624, 0.92068413]])

In [29]:
np.random.randint(1,201,2)

array([ 17, 104])

In [30]:
np.random.randint(1,20)

17

In [31]:
np.random.randint(1,201, (3,4))

array([[ 57,  33, 143,  60],
       [ 20,  13, 109,  26],
       [180, 174, 147, 115]])

In [34]:
np.random.randint(4)

1

In [35]:
np.random.rand(4)

array([0.00778984, 0.57689366, 0.25334629, 0.94949333])

In [36]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [37]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [38]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [39]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [40]:
arr = np.arange(0,25)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
arr.max(), arr.min()

(24, 0)

In [45]:
arr.argmax()

24

In [46]:
arr = np.random.randint(0,323,9)

In [47]:
arr

array([ 40, 132,  63, 245, 316, 220, 192, 110,   5])

In [48]:
arr.max()

316

In [49]:
arr.argmax()

4

In [50]:
arr.min(), arr.argmin()

(5, 8)

In [51]:
arr.dtype

dtype('int64')

In [52]:
arr.shape

(9,)

In [53]:
arr.reshape(3,3)

array([[ 40, 132,  63],
       [245, 316, 220],
       [192, 110,   5]])

In [65]:
arr.shape
#this (9,0) indicates 1-D vector

(9,)

In [55]:
arr.reshape(3,3).shape

(3, 3)

In [57]:
arr2 = arr.reshape(1,9)

In [58]:
arr2

array([[ 40, 132,  63, 245, 316, 220, 192, 110,   5]])

In [59]:
arr2.shape

(1, 9)

In [63]:
#notice the two squre brackets in arr2 and not in arr

In [61]:
arr

array([ 40, 132,  63, 245, 316, 220, 192, 110,   5])

In [62]:
arr.shape

(9,)